### ISSUE TITLE
Format convert 

### ISSUE THREAD

**Issue by TuoBaed** [riscv2os/riscv2os#1]
请问，方便提供.doc格式或者.pdf格式的文件下载链接吗？.md文档还是不太适合做标注以及笔记。

**Comment by ianchen0119** [comment]
@TuoBaed 
You can clone this project and convert all md files to pdf.
```
git clone https://github.com/riscv2os/riscv2os.wiki.git
```
markdown converter:
https://www.markdowntopdf.com/

**Comment by huangzixun123** [comment]
Hi, i have received your email. Thanks!This is a auto-reply email.
